select
  percentile_cont(score_diff, 0) over() AS min,
  percentile_cont(score_diff, 0.1) over() AS q10,
  percentile_cont(score_diff, 0.2) over() AS q20,
  percentile_cont(score_diff, 0.3) over() AS q30,
  percentile_cont(score_diff, 0.4) over() AS q40,
  percentile_cont(score_diff, 0.5) over() AS q50,
  percentile_cont(score_diff, 0.6) over() AS q60,
  percentile_cont(score_diff, 0.7) over() AS q70,
  percentile_cont(score_diff, 0.75) over() AS q75,
  percentile_cont(score_diff, 0.8) over() AS q80,
  percentile_cont(score_diff, 0.9) over() AS q90,
  percentile_cont(score_diff, 0.95) over() AS q95,
  percentile_cont(score_diff, 0.96) over() AS q96,
  percentile_cont(score_diff, 0.97) over() AS q97,
  percentile_cont(score_diff, 0.98) over() AS q98,
  percentile_cont(score_diff, 0.99) over() AS q99,
  percentile_cont(score_diff, 1) over() AS max,
from fields_of_study.score_comparison
limit 1
